export const UPDATE_USER_REGISTER = 'UPDATE_USER_REGISTER';
export const UPDATE_FIRSTNAME = 'UPDATE_FIRSTNAME';
export const CLEAR_USER_REGISTER = 'CLEAR_USER_REGISTER';
export const UPDATE_LASTNAME = 'UPDATE_LASTNAME';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';


